use std::fs;
use std::path::PathBuf;

fn main() {
    println!("cargo:rerun-if-changed=proto");

    // When the `console` feature is on, generate an asset map that embeds the
    // built dashboard (dashboard/dist) into the binary. In-house codegen (no
    // extra crate): emits a slice of (path, mime, &[u8]) the server serves.
    if std::env::var_os("CARGO_FEATURE_CONSOLE").is_some() {
        embed_dashboard();
    }

    let proto_dir = PathBuf::from("proto");
    if !proto_dir.exists() {
        // Allow scaffold to compile even before .proto files are vendored.
        // proto/ is vendored per SPEC.md (milestone M1).
        return;
    }

    let mut protos: Vec<PathBuf> = Vec::new();
    collect_protos(&proto_dir, &mut protos);

    if protos.is_empty() {
        return;
    }

    // Vendored protoc so the build is hermetic.
    if std::env::var_os("PROTOC").is_none() {
        let path = protoc_bin_vendored::protoc_bin_path()
            .expect("vendored protoc binary unavailable for this target");
        std::env::set_var("PROTOC", path);
    }

    let mut config = prost_build::Config::new();
    config.out_dir(PathBuf::from(std::env::var("OUT_DIR").unwrap()));
    // Single include file aggregating every generated package; main.rs can
    // pull all of them with one `include!`.
    config.include_file("_includes.rs");

    if let Err(e) = config.compile_protos(&protos, &[proto_dir]) {
        panic!("failed to compile protos: {e}");
    }
}

/// Generate `$OUT_DIR/dashboard_assets.rs`: a static slice of every file under
/// `dashboard/dist` as `(url_path, mime, &'static [u8])`, embedded via
/// `include_bytes!`. The server (api.rs, under `feature = "console"`) includes
/// and serves it. Fails the build if the dashboard hasn't been built yet, since
/// the feature explicitly promises an embedded console.
fn embed_dashboard() {
    use std::fmt::Write as _;

    let dist = PathBuf::from("dashboard/dist");
    let manifest = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    if !dist.join("index.html").exists() {
        panic!(
            "feature `console` is on but {dist:?}/index.html is missing — build the \
             dashboard first: (cd dashboard && npm install && npm run build)"
        );
    }
    println!("cargo:rerun-if-changed=dashboard/dist");

    let mut files: Vec<PathBuf> = Vec::new();
    collect_files(&dist, &mut files);
    files.sort();

    let mut code = String::from(
        "// @generated by build.rs — embedded dashboard assets.\n\
         pub static DASHBOARD_ASSETS: &[(&str, &str, &[u8])] = &[\n",
    );
    for f in &files {
        // URL path is the file path relative to dist, forward-slashed, leading '/'.
        let rel = f.strip_prefix(&dist).unwrap().to_string_lossy().replace('\\', "/");
        let abs = PathBuf::from(&manifest).join(f);
        let abs = abs.to_string_lossy().replace('\\', "/");
        let mime = mime_for(f);
        writeln!(
            code,
            "    (\"/{rel}\", \"{mime}\", include_bytes!(\"{abs}\")),"
        )
        .unwrap();
    }
    code.push_str("];\n");

    let out = PathBuf::from(std::env::var("OUT_DIR").unwrap());
    fs::write(out.join("dashboard_assets.rs"), code).expect("write dashboard_assets.rs");
}

fn collect_files(dir: &PathBuf, out: &mut Vec<PathBuf>) {
    let Ok(entries) = fs::read_dir(dir) else { return };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect_files(&path, out);
        } else {
            out.push(path);
        }
    }
}

fn mime_for(path: &std::path::Path) -> &'static str {
    match path.extension().and_then(|s| s.to_str()) {
        Some("html") => "text/html; charset=utf-8",
        Some("js") | Some("mjs") => "text/javascript; charset=utf-8",
        Some("css") => "text/css; charset=utf-8",
        Some("json") => "application/json",
        Some("svg") => "image/svg+xml",
        Some("png") => "image/png",
        Some("jpg") | Some("jpeg") => "image/jpeg",
        Some("gif") => "image/gif",
        Some("webp") => "image/webp",
        Some("ico") => "image/x-icon",
        Some("woff2") => "font/woff2",
        Some("woff") => "font/woff",
        Some("ttf") => "font/ttf",
        Some("txt") => "text/plain; charset=utf-8",
        Some("map") => "application/json",
        _ => "application/octet-stream",
    }
}

fn collect_protos(dir: &PathBuf, out: &mut Vec<PathBuf>) {
    let Ok(entries) = fs::read_dir(dir) else { return };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect_protos(&path, out);
        } else if path.extension().and_then(|s| s.to_str()) == Some("proto") {
            out.push(path);
        }
    }
}
