//! ruwa: API-first multi-tenant WhatsApp Web client.
//!
//! Architecture: each HTTP request resolves a `SessionId`, looks up the
//! per-tenant `Session` (which owns its WS connection, Signal store, and
//! event bus), and dispatches.

mod api;
mod crypto;
mod egress;
mod error;
mod media;
mod protocol;
mod session;
mod store;

#[allow(clippy::all)]
#[allow(non_snake_case, non_camel_case_types, non_upper_case_globals, dead_code)]
mod proto {
    // Generated by build.rs from proto/. One module per WA package.
    include!(concat!(env!("OUT_DIR"), "/_includes.rs"));
}

use std::net::SocketAddr;
use std::sync::Arc;

use anyhow::Context;
use tracing_subscriber::{layer::SubscriberExt, util::SubscriberInitExt, EnvFilter};

use crate::session::SessionManager;
use crate::store::Store;

#[tokio::main]
async fn main() -> anyhow::Result<()> {
    let filter = EnvFilter::try_from_default_env().unwrap_or_else(|_| EnvFilter::new("info"));
    // Log-ring capture layer: forward events at/above a configured severity to a
    // channel that a background flusher persists to the store, so the Console can
    // show diagnostics that survive a restart/deploy. The channel is created here
    // (before subscriber init) so even boot logs are captured; the flusher is
    // spawned once the store is open. The EnvFilter above is still the master
    // gate, so the ring never sees anything quieter than RUST_LOG allows.
    let (log_tx, log_rx) = tokio::sync::mpsc::unbounded_channel::<LogLine>();
    let ring_min_sev = std::env::var("RUWA_LOG_RING_LEVEL")
        .ok()
        .map(|s| crate::store::log_level_sev(&s))
        .unwrap_or(2); // default INFO
    tracing_subscriber::registry()
        .with(filter)
        .with(tracing_subscriber::fmt::layer())
        .with(LogRingLayer {
            tx: log_tx,
            min_sev: ring_min_sev,
        })
        .init();

    let store_path = std::env::var("RUWA_STORE")
        .unwrap_or_else(|_| "./data/ruwa.db".to_string());
    if let Some(parent) = std::path::Path::new(&store_path).parent() {
        std::fs::create_dir_all(parent).ok();
    }

    let store = Store::open(&store_path).context("opening store")?;
    let store = Arc::new(store);

    // Initialize at-rest encryption early so its status is logged at boot (and
    // a misconfigured RUWA_DB_ENCRYPTION_KEY surfaces immediately, not on first
    // secret write). Off by default; see crypto::vault.
    if crate::crypto::vault::enabled() {
        tracing::info!("RUWA_DB_ENCRYPTION_KEY set — secret columns encrypted at rest");
    } else {
        tracing::warn!("RUWA_DB_ENCRYPTION_KEY not set — secret columns stored in plaintext");
    }

    let api_token = std::env::var("RUWA_API_TOKEN").unwrap_or_else(|_| {
        let t = crate::session::uuid_v4();
        tracing::warn!(token = %t, "RUWA_API_TOKEN not set; generated ephemeral token");
        t
    });

    let manager = Arc::new(SessionManager::new(store.clone()));
    manager.restore_all().await.context("restoring sessions")?;
    // Revive paired sessions a restart left disconnected, so a deploy/restart
    // doesn't leave WhatsApp offline until a manual /connect. The per-session
    // reconnect loop + keepalive watchdog keep them up after that.
    let revived = manager.autoconnect_restored();
    if revived > 0 {
        tracing::info!(sessions = revived, "auto-connecting restored sessions on boot");
    }

    let readonly = matches!(
        std::env::var("RUWA_READONLY").as_deref(),
        Ok("1") | Ok("true") | Ok("yes")
    );
    if readonly {
        tracing::warn!("RUWA_READONLY=1 — mutating routes will return 403");
    }

    // Background retention sweep (opt-in via RUWA_RETENTION_* envs). Disabled
    // entirely unless a sweep interval AND at least one pruning knob are set —
    // an unconfigured deployment never deletes data.
    let retention = crate::session::RetentionConfig::from_env();
    if retention.sweep_secs > 0 && retention.any_enabled() {
        let mgr = manager.clone();
        let interval = std::time::Duration::from_secs(retention.sweep_secs.max(60));
        tracing::info!(?retention, "retention sweep enabled");
        tokio::spawn(async move {
            loop {
                tokio::time::sleep(interval).await;
                match mgr.prune_once(&retention) {
                    Ok(s) if s != crate::session::PruneStats::default() => {
                        tracing::info!(?s, "retention sweep pruned rows");
                    }
                    Ok(_) => {}
                    Err(e) => tracing::warn!(error = %e, "retention sweep failed"),
                }
            }
        });
    }

    // Background metrics sampler: snapshot the in-memory `/metrics` counters and
    // gauges into the store on a fixed cadence so the Console can chart history
    // that survives restarts (the live endpoint is reset-to-zero atomics). Always
    // on — growth is bounded by an hourly age-prune. Cadence + retention tunable
    // via RUWA_METRICS_SAMPLE_SECS (default 60) and RUWA_METRICS_MAX_AGE_DAYS (7).
    {
        let mgr = manager.clone();
        let sample_secs = std::env::var("RUWA_METRICS_SAMPLE_SECS")
            .ok()
            .and_then(|s| s.parse::<u64>().ok())
            .filter(|n| *n > 0)
            .unwrap_or(60);
        let retain_days = std::env::var("RUWA_METRICS_MAX_AGE_DAYS")
            .ok()
            .and_then(|s| s.parse::<i64>().ok())
            .filter(|n| *n > 0)
            .unwrap_or(7);
        tracing::info!(sample_secs, retain_days, "metrics sampler enabled");
        tokio::spawn(async move {
            let mut tick =
                tokio::time::interval(std::time::Duration::from_secs(sample_secs));
            tick.set_missed_tick_behavior(tokio::time::MissedTickBehavior::Skip);
            let mut last_prune = 0i64;
            loop {
                tick.tick().await;
                let now = chrono::Utc::now().timestamp();
                if let Err(e) = mgr.persist_metrics(now) {
                    tracing::warn!(error = %e, "metrics sampler: persist failed");
                }
                // Bound growth: age-prune at most hourly.
                if now - last_prune >= 3_600 {
                    last_prune = now;
                    let cutoff = now - retain_days * 86_400;
                    match mgr.prune_metrics(cutoff) {
                        Ok(n) if n > 0 => tracing::info!(pruned = n, "metrics sampler: pruned old samples"),
                        Ok(_) => {}
                        Err(e) => tracing::warn!(error = %e, "metrics sampler: prune failed"),
                    }
                }
            }
        });
    }

    // Log-ring flusher: drain captured tracing events from the channel and batch
    // them into the store, bounding the ring to the newest RUWA_LOG_RING_MAX_ROWS
    // (default 20k) and dropping anything past RUWA_LOG_RING_MAX_AGE_DAYS (7).
    // The capture layer only touches the channel (never the DB), so logging stays
    // off the DB hot path; persistence happens here, out of band.
    {
        let store = store.clone();
        let max_rows = std::env::var("RUWA_LOG_RING_MAX_ROWS")
            .ok()
            .and_then(|s| s.parse::<i64>().ok())
            .filter(|n| *n > 0)
            .unwrap_or(20_000);
        let max_age_days = std::env::var("RUWA_LOG_RING_MAX_AGE_DAYS")
            .ok()
            .and_then(|s| s.parse::<i64>().ok())
            .filter(|n| *n > 0)
            .unwrap_or(7);
        let mut rx = log_rx;
        tokio::spawn(async move {
            let mut tick = tokio::time::interval(std::time::Duration::from_secs(2));
            tick.set_missed_tick_behavior(tokio::time::MissedTickBehavior::Skip);
            let mut last_prune = 0i64;
            loop {
                tick.tick().await;
                // Drain what's queued (bounded per tick; the rest waits, never lost).
                let mut buf: Vec<LogLine> = Vec::new();
                while let Ok(line) = rx.try_recv() {
                    buf.push(line);
                    if buf.len() >= 1_000 {
                        break;
                    }
                }
                if !buf.is_empty() {
                    let rows: Vec<(i64, i32, &str, &str, &str)> = buf
                        .iter()
                        .map(|l| (l.ts, l.sev, l.level, l.target.as_str(), l.message.as_str()))
                        .collect();
                    if let Err(e) = store.log_ring_insert_batch(&rows) {
                        // Don't tracing::warn here — it would re-enter the ring.
                        eprintln!("log-ring flusher: insert failed: {e}");
                    }
                }
                let now = chrono::Utc::now().timestamp();
                if now - last_prune >= 300 {
                    last_prune = now;
                    let cutoff_ms = (now - max_age_days * 86_400) * 1_000;
                    let _ = store.log_ring_prune(max_rows, cutoff_ms);
                }
            }
        });
    }

    // Media storage backend: default DB, or an S3-compatible bucket when
    // RUWA_MEDIA_STORE=s3 (fail fast if it's set but misconfigured).
    let media_store = crate::media::S3Config::from_env()
        .map_err(|e| anyhow::anyhow!("media storage config: {e}"))?
        .map(Arc::new);
    if media_store.is_some() {
        tracing::info!("media storage: S3-compatible bucket (RUWA_MEDIA_STORE=s3)");
    }

    let app = api::router(api::AppState {
        manager: manager.clone(),
        api_token: Arc::new(api_token),
        readonly,
        media_store,
    });

    // Bind address: explicit RUWA_BIND wins; otherwise honor a platform-provided
    // PORT (Railway/Heroku/Fly set it) by listening on 0.0.0.0:$PORT; else the
    // local default. Containers must bind 0.0.0.0, not loopback.
    let bind: SocketAddr = std::env::var("RUWA_BIND")
        .or_else(|_| std::env::var("PORT").map(|p| format!("0.0.0.0:{p}")))
        .unwrap_or_else(|_| "127.0.0.1:8080".to_string())
        .parse()
        .context("parsing RUWA_BIND / PORT")?;

    tracing::info!(%bind, "ruwa listening");
    let listener = tokio::net::TcpListener::bind(bind).await?;
    axum::serve(listener, app)
        .with_graceful_shutdown(shutdown_signal())
        .await?;

    // Listener has stopped accepting (SIGTERM / Ctrl-C). Wind down each
    // session's connection task — flush queued outbound, close sockets,
    // park statuses — before the process exits.
    tracing::info!("shutdown signal received; draining sessions");
    manager.shutdown().await;
    tracing::info!("graceful shutdown complete");
    Ok(())
}

/// Resolve when the process receives SIGTERM (container stop) or Ctrl-C.
/// Drives `axum::serve`'s graceful shutdown: stop accepting, finish in-flight
/// requests, then hand off to `SessionManager::shutdown`.
async fn shutdown_signal() {
    let ctrl_c = async {
        tokio::signal::ctrl_c()
            .await
            .expect("install Ctrl-C handler");
    };

    #[cfg(unix)]
    let terminate = async {
        tokio::signal::unix::signal(tokio::signal::unix::SignalKind::terminate())
            .expect("install SIGTERM handler")
            .recv()
            .await;
    };
    #[cfg(not(unix))]
    let terminate = std::future::pending::<()>();

    tokio::select! {
        _ = ctrl_c => {}
        _ = terminate => {}
    }
}

/// One captured tracing event, en route from the capture layer to the flusher.
struct LogLine {
    ts: i64, // unix milliseconds
    sev: i32,
    level: &'static str,
    target: String,
    message: String,
}

/// Collects an event's `message` field plus any structured key/values into a
/// single human-readable string (`message key=value …`).
#[derive(Default)]
struct LogFieldVisitor {
    message: String,
    kvs: String,
}

impl tracing::field::Visit for LogFieldVisitor {
    fn record_debug(&mut self, field: &tracing::field::Field, value: &dyn std::fmt::Debug) {
        use std::fmt::Write;
        let name = field.name();
        if name == "message" {
            let _ = write!(self.message, "{value:?}");
        } else if name.starts_with("log.") {
            // Bridged `log`-crate records carry log.target/module_path/file/line
            // metadata fields — noise in a human log line; drop them.
        } else {
            let _ = write!(self.kvs, " {name}={value:?}");
        }
    }
}

/// `tracing` layer that forwards events (≥ `min_sev`) to the flusher channel.
/// Does no I/O and never blocks — just formats and `send`s — so it's safe to run
/// in any logging context (including while locks are held).
struct LogRingLayer {
    tx: tokio::sync::mpsc::UnboundedSender<LogLine>,
    min_sev: i32,
}

impl<S> tracing_subscriber::Layer<S> for LogRingLayer
where
    S: tracing::Subscriber + for<'a> tracing_subscriber::registry::LookupSpan<'a>,
{
    fn on_event(
        &self,
        event: &tracing::Event<'_>,
        _ctx: tracing_subscriber::layer::Context<'_, S>,
    ) {
        let meta = event.metadata();
        let sev = match *meta.level() {
            tracing::Level::ERROR => 4,
            tracing::Level::WARN => 3,
            tracing::Level::INFO => 2,
            tracing::Level::DEBUG => 1,
            tracing::Level::TRACE => 0,
        };
        if sev < self.min_sev {
            return;
        }
        let mut v = LogFieldVisitor::default();
        event.record(&mut v);
        let message = if v.kvs.is_empty() {
            v.message
        } else {
            format!("{}{}", v.message, v.kvs)
        };
        // Fire-and-forget; drop the line if the flusher has gone away.
        let _ = self.tx.send(LogLine {
            ts: chrono::Utc::now().timestamp_millis(),
            sev,
            level: meta.level().as_str(),
            target: meta.target().to_string(),
            message,
        });
    }
}
